apiVersion: v1
kind: ConfigMap

metadata:
  name: gaming-config

data:
  APP_NAME: "Gaming Platform"
  APP_VERSION: "v3.0.0"
  ENVIRONMENT: "development"
  WELCOME_MESSAGE: "Welcome to Gaming Platform running on Kubernetes"