name: Gaming Platform CI/CD Pipeline

on:
push:
branches:
- main
tags:
- 'v*'

jobs:
validate-code:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.11"

  - name: Install Dependencies
    run: pip install -r requirements.txt

  - name: Validate Python Code
    run: python -m py_compile app.py
```

build-artifact:
needs: validate-code
runs-on: ubuntu-latest

```
steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Create Artifact Folder
    run: |
      mkdir artifact
      cp app.py artifact/
      cp Dockerfile artifact/
      cp requirements.txt artifact/

  - name: Upload Artifact
    uses: actions/upload-artifact@v4
    with:
      name: gaming-platform-build
      path: artifact/
```

docker-release:
if: startsWith(github.ref, 'refs/tags/v')
needs: build-artifact
runs-on: ubuntu-latest

```
permissions:
  contents: write

steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Get Short SHA
    id: vars
    run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  - name: Login To Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  - name: Build Docker Image
    run: |
      docker build -t anjali146/gaming-platform:${{ github.ref_name }} .
      docker tag anjali146/gaming-platform:${{ github.ref_name }} anjali146/gaming-platform:${{ steps.vars.outputs.sha_short }}

  - name: Push Version Tag
    run: docker push anjali146/gaming-platform:${{ github.ref_name }}

  - name: Push SHA Tag
    run: docker push anjali146/gaming-platform:${{ steps.vars.outputs.sha_short }}

  - name: Create GitHub Release
    uses: softprops/action-gh-release@v2
    with:
      generate_release_notes: true
```
